# Credentials to pull images from docker registry
imageCredentials:
    registry: index.docker.io
    username: invalid_username
    password: invalid_password

smtp:
    host: smtp.ethereal.email
    port: 586
    username: username
    password: password

imap:
    host: imap.ethereal.email
    port: 993
    username: username
    password: password

numberReplicas:
    frontend: 1
    backend: 1
    debugger: 0

minio:
  accesskey: minio # base 64 encoded "minio" (echo -n 'minio' | base64)
  secretkey: minio123 # based 64 encoded "minio123" (echo -n 'minio123' | base64)

# Hosts used for Ingress configuration
hosts:
    frontend: k8s.streammyiot.com
    websocketserver: ws.streammyiot.com

# Docket image tag
tag: latest

# Enable jaeger tracing
jaeger_tracing: false

# Sets resource limits lower to test locally
# or on smaller cluster when set to true
less_resources: true
