apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-operator-default-config
  namespace: cassandra
data:
  {{ if .Values.less_resources }}
  nodes: "1"
  {{ else }}
  nodes: {{ .Values.cassandra.nodes | quote}}
  {{ end }}
  cassandraImage: gcr.io/cassandra-operator/cassandra-3.11.6:v6.4.0
  sidecarImage: gcr.io/cassandra-operator/instaclustr-icarus:1.0.1
  {{ if .Values.less_resources }}
  memory: 0.5Gi
  {{ else }}
  memory: {{ .Values.cassandra.memory}}
  {{ end }}
  {{ if .Values.less_resources }}
  disk: 0.5Gi
  {{ else }}
  disk: {{ .Values.cassandra.disk }}
  {{ end }}
  diskMedium: ""
