apiVersion: v1
data:
  {{ $secret := (lookup "v1" "Secret" "iff" "keycloak-client-secret-fusion-backend") }}
  keycloak: |
    {
    "realm": "iff",
    {{ if .Values.less_resources }}
    "auth-server-url": "http://keycloak.local/auth",
    {{ else }}
    "auth-server-url": "https://keycloak.local/auth",
    {{ end }}
    "ssl-required": "external",
    "resource": "{{ $secret.data.CLIENT_ID | b64dec }}",
    "verify-token-audience": true,
    "credentials":
      {
      "secret": "{{ $secret.data.CLIENT_SECRET | b64dec }}"
      },
    "use-resource-role-mappings": true,
    "confidential-port": 0,
    "policy-enforcer": {}
    }
  keycloak-fusion-backend-secret: "{{ $secret.data.CLIENT_SECRET | b64dec }}"

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fusion-config
  selfLink: /api/v1/namespaces/cloudfest-1/configmaps/fusion-config
