apiVersion: v1
data:
  keycloak: |
    {
    "realm": "OISP",
    "auth-server-url": "{{ .Values.keycloak.fusionBackend.authServerUrl }}",
    "ssl-required": "external",
    "resource": "fusion-backend",
    "verify-token-audience": true,
    "credentials":
      {
      "secret": "{{ .Values.keycloak.fusionBackend.secret }}"
      },
    "use-resource-role-mappings": true,
    "confidential-port": 0,
    "policy-enforcer": {}
    }
  keycloak-fusion-backend-secret: {{ .Values.keycloak.fusionBackend.secret }}

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: fusion-config
  selfLink: /api/v1/namespaces/cloudfest-1/configmaps/fusion-config
