version: 2
jobs:
  e2e-test:
    machine:
      enabled: true
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: Setup test environment
        command: |
          cd util
          export PATH=$PATH:/snap/bin && bash setup-ubuntu18.04.sh
          npm install nodemailer
    - run:
        name: Build and deploy images
        command: |
          cd util
          export PATH=$PATH && bash build-and-import-images.sh
    - run:
        name: Deploy OISP
        command: export PATH=$PATH:/snap/bin && export DOCKERUSER=unused && DOCKERPASS=unused && make deploy-oisp-test
    - run:
        name: Run tests
        command: export PATH=$PATH:/snap/bin && make wait-until-ready && make test
    environment:
    - shell: /bin/bash
    - TERM: xterm
    - TZ: Europe/Berlin
workflows:
  version: 2
  workflow:
    jobs:
    - e2e-test
