apiVersion: "v1"
kind: "Secret"
metadata:
  name: "{{ .Values.postgres.username | replace "_" "-"}}.{{ .Values.postgres.clustername }}.credentials"
  labels:
    application: spilo
    cluster-name: {{ .Values.postgres.clustername }}
    team: {{ .Values.postgres.team }}
data:
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.pgSuperuserName }}.{{ .Values.postgres.clustername }}.credentials
  labels:
    application: spilo
    cluster-name: {{ .Values.postgres.clustername }}
    team: {{ .Values.postgres.team }}
data:
  username: {{ .Values.postgres.pgSuperuserName | b64enc }}
  password: {{ .Values.postgres.pgSuperuserPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.pgSuperuserName }}.{{ .Values.postgres.clustername }}.credentials.{{ .Values.postgres.clustersuffix }}
  labels:
    application: spilo
    cluster-name: {{ .Values.postgres.clustername }}
    team: {{ .Values.postgres.team }}
data:
  username: {{ .Values.postgres.pgSuperuserName | b64enc }}
  password: {{ .Values.postgres.pgSuperuserPassword | b64enc }}