apiVersion: v1
data:
  # These jwt keys must be the same with the defined keys in oisp-realm-secret
  jwt.privatekey: {{ .Values.jwt.private }}
  jwt.publickey: {{ .Values.jwt.public }}
  jwt.x509: {{ .Values.jwt.x509 }}
  postgres.password: cGFzc3dvcmQ=
  mqtt.key: Um1rZmYxdWZyNE9pM3BnQU1sUk5Bdz09
kind: Secret
metadata:
  creationTimestamp: null
  name: oisp-secrets
type: Opaque
