apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  ports:
  - port: 8089
    name: dashboard
  - port: 5557
    name: "5557"
  - port: 5558
    name: "5558"
  selector:
    app: locust-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: locust-master
  name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust-master
        image: oisp/debugger
        volumeMounts:
        - name: locust-volume
          mountPath: /locust
        workingDir: /locust
        command: ["locust", "--host", "{{.Values.oisp.url}}", "--master"]
        resources:
          requests:
            cpu: "200m"
      imagePullSecrets:
        - name: dockercred
      volumes:
      - name: locust-volume
        configMap:
          name: locustfile
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: locust-master
spec:
  rules:
  - host: k8s.streammyiot.com
    http:
      paths:
      - path: "/locust"
        backend:
          serviceName: locust-master
          servicePort: 8089