apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraDataCenter
datacenter: {{ .Release.Namespace }}
cluster: {{ .Values.cassandra.cluster }}
host: cassandra-oisp-{{ .Release.Namespace }}-nodes.svc.cluster.local #note: datacenter and cluster have influence on how the name is built
metadata:
  name: {{ .Release.Namespace }}
  namespace: cassandra
spec:
  serviceAccountName: cassandra
