apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: {{ .Values.cassandra.name }}
  namespace: cassandra
spec:
  clusterName: {{ .Values.cassandra.cluster }}
  serverType: cassandra
  serverVersion: "4.0.3"
  managementApiAuth:
    insecure: {}
  {{ if .Values.less_resources }}
  size: 1
  {{ else }}
  size: {{ .Values.cassandra.nodes }}
  {{ end }}
  storageConfig:
      cassandraDataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            {{ if .Values.less_resources }}
            storage: 1Gi
            {{ else }}
            storage: {{ .Values.cassandra.disk }}
            {{ end }}
  dockerImageRunsAsCassandra: false
  podTemplateSpec:
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: "server-system-logger"
          image: k8ssandra/system-logger:v1.11.0

  resources:
    {{ if .Values.less_resources }}
    requests:
      memory: 400Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 200m
    {{ else }}
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
    {{ end }}
  racks:
    - name: {{ .Values.cassandra.rack }}
  config:
    jvm-server-options:
    {{ if .Values.less_resources }}
      initial_heap_size: "200M"
      max_heap_size: "200M"
    {{ else }}
      initial_heap_size: "500M"
      max_heap_size: "500M"
    {{ end }}
    cassandra-yaml:
      num_tokens: 16
      authenticator: AllowAllAuthenticator
      authorizer: AllowAllAuthorizer
      role_manager: CassandraRoleManager
