apiVersion: v1
kind: Service
metadata:
  labels:
    app: hbase-region
  name: hbase-region
spec:
  clusterIP: None
  ports:
  - name: "8020"
    port: 8020
  selector:
    app: hbase-region
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-region
  labels:
    app: hbase-region
spec:
  serviceName: hbase-region
  {{ if .Values.less_resources }}
  replicas: 1
  {{ else }}
  replicas: {{ .Values.hbaseScale.dataNodes }}
  {{ end }}
  selector:
    matchLabels:
      app: hbase-region
  template:
    metadata:
      labels:
        app: hbase-region
    spec:
      containers:
      - name: hbase-region
        image: oisp/hbase:{{ .Values.tag }}
        resources:
          {{ if .Values.less_resources }}
          requests:
            cpu: 50m
          {{ else }}
          limits:
            memory: 1G
            cpu: 1
          requests:
            memory: 500M
            cpu: 500m
          {{ end }}
        env:
        - name: REGIONSERVERS
          value: hbase-region-0.hbase-region
        - name: ZOOKEEPER
          value: {{ .Values.zookeeper.servers }}
        - name: HDFS_NAMENODE
          value: hdfs-namenode
        - name: HADOOP_USER_NAME
          value: root
        args:
        - "/opt/wait-for-it.sh"
        - {{ .Values.hbaseScale.masterReady }}
        - "-t"
        - "300"
        - "--"
        - "/bin/bash"
        - "/opt/entrypoint-region.sh"
        ports:
        - containerPort: 9090
        - containerPort: 16020
        - containerPort: 16030
      imagePullSecrets:
      - name: dockercred
