apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: kafka
    port: 9092
  - name: kafka2
    port: 9093
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: bitnami/kafka:1.1.1
        resources:
          {{ if .Values.less_resources }}
          requests:
            cpu: 50m
          {{ else }}
          requests:
            memory: 1G
            cpu: 300m
          {{ end }}
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENERS
          value: LISTENER_BOB://0.0.0.0:9092,LISTENER_FRED://0.0.0.0:9093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: LISTENER_BOB://kafka:9092,LISTENER_FRED://localhost:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_BOB
        ports:
        - containerPort: 9092
        - containerPort: 9093
        readinessProbe:
          tcpSocket:
            port: 9092
