---
apiVersion: v1
data:
  accesskey: {{ .Values.minio.adminAccessKey | toString | b64enc }}
  secretkey: {{ .Values.minio.adminSecretKey | toString | b64enc }}
kind: Secret
metadata:
  name: oisp-creds-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: {{ .Values.minio.userAccessKey | toString | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.userSecretKey | toString | b64enc }}
kind: Secret
metadata:
  name: minio-user
  namespace: {{ .Release.Namespace }}
type: Opaque
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: oisp-minio-tenant
  namespace: {{ .Release.Namespace }}
spec:
  env:
  - name: "MINIO_STORAGE_CLASS_STANDARD"
    value: "EC:2"
  - name: "MINIO_BROWSER"
    value: "on"
  requestAutoCert: false
  credsSecret:
    name: oisp-creds-secret
  users:
    - name: minio-user
  pools:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.minio.storageSize }}
