apiVersion: oisp.org/v1
kind: BeamService
metadata:
  name: rule-engine
spec:
  entryClass: "org.oisp.RuleEngineBuild"
  tokens:
  - user: {{ .Values.ruleEngine.username }}
    password: {{ .Values.ruleEngine.password }}
  args:
    runner: FlinkRunner
    {{ if .Values.production }}
    checkpointingInterval: {{ .Values.ruleEngine.checkpointingInterval | quote }}
    {{ end }}
    streaming: "true"
    JSONConfig:
      format: |
        {{`{{
        "application_name": "rule_engine_dashboard",
        "dashboard_strict_ssl": false,
        "dashboard_url": "http://{config[ruleEngineConfig][frontendUri]}",
        "dashboard_username": "{config[ruleEngineConfig][username]}",
        "dashboard_password": "{config[ruleEngineConfig][password]}",
        "kafka_servers": "{config[kafkaConfig][uri]}",
        "kafka_zookeeper_quorum": "{config[zookeeperConfig][zkCluster]}" ,
        "kafka_observations_topic": "{config[kafkaConfig][topicsObservations]}",
        "kafka_rule_engine_topic": "{config[kafkaConfig][topicsRuleEngine]}",
        "kafka_heartbeat_topic": "{config[kafkaConfig][topicsHeartbeatName]}",
        "kafka_heartbeat_interval": "{config[kafkaConfig][topicsHeartbeatInterval]}",
        "token": "{tokens[rule_engine@intel.com]}"
        }}`}}
      encode: base64
  package:
    url: {{ .Values.ruleEngine.url }}
    username: {{ .Values.ruleEngine.ftpUsername }}
    password: {{ .Values.ruleEngine.ftpPassword }}
