apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: "2181"
    port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper:3.4.13
        name: zookeeper
        resources:
          {{ if .Values.less_resources }}
          requests:
            cpu: 50m
          {{ else }}
          requests:
            memory: 100m
            cpu: 100m
          {{ end }}
        env:
        - name: ZOO_SERVERS
          value: "server.1=0.0.0.0:2888:3888"
        ports:
        - containerPort: 2181
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: zookeeper-data
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
