kind: PersistentVolume
apiVersion: v1
metadata:
  name: storage-postgres
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres/"