apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: {{ .Values.flink.restPort }}
    targetPort: {{ .Values.flink.restPort }}
  selector:
    app: flink
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-sql-gateway
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: {{ .Values.flink.sqlClientPort }}
    targetPort: {{ .Values.flink.sqlClientPort }}
  selector:
    app: flink
    component: jobmanager
