apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flink.url }}
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: ui
    port: {{ .Values.flink.restPort }}
  selector:
    app: flink
    component: jobmanager
