apiVersion: v1
appVersion: "3.0.0-alpha.1"
description: OISP Helm Chart
name: oisp
version: 3.0.0-alpha.1
dependencies:
- name: emqx
  alias: emqxtest
  version: 4.4.5
  repository: https://repos.emqx.io/charts
  condition: less_resources
- name: emqx
  alias: emqx
  version: 4.4.5
  repository: https://repos.emqx.io/charts
  condition: production
- name: reloader
  alias: reloader
  version: 0.0.89
  repository: https://stakater.github.io/stakater-charts
