apiVersion: v1
appVersion: "1.0.4"
description: OISP Helm Chart
name: oisp
version: 0.1.0
dependencies:
- name: keycloak
  version: 6.0.4
  repository: https://codecentric.github.io/helm-charts
- name: kafka
  version: 0.20.8
  repository: "@incubator"
  condition: production
- name: kafka
  alias: kafkatest
  version: 0.20.8
  repository: "@incubator"
  condition: less_resources
- name: emqx
  alias: emqxtest
  version: 4.2.6
  repository: https://repos.emqx.io/charts
  condition: less_resources
- name: emqx
  alias: emqx
  version: 4.2.6
  repository: https://repos.emqx.io/charts
  condition: production
