# Credentials to pull images from docker registry
imageCredentials:
    registry: index.docker.io
    username: invalid_username
    password: invalid_password

smtp:
    host: debugger
    port: 2525
    username: username
    password: password

imap:
    host: imap.ethereal.email
    port: 993
    username: imaptest@streammyiot.com
    password: P@ssword123!

numberReplicas:
    frontend: 1
    backend: 1
    debugger: 0

minio:
  accesskey: minio
  secretkey: minio123

grafana:
  admin: grafana
  password: intel123

mqtt:
  broker:
    username: username
    password: password

# Gearpump username and password are legacy, they can be removed safely
# after the rule-engine is updated to ignore them.
ruleEngine:
  username: "rule_engine@intel.com"
  password: password
  gearpump:
    username: admin
    password: password

websocketServer:
  username: api_actuator
  password: password

# Hosts used for Ingress configuration
hosts:
    frontend: latest.streammyiot.com
    websocketserver: ws.latest.streammyiot.com
    mqttserver: mqtt.latest.streammyiot.com

systemuser:
  username: gateway@intel.com
  password: 7d501829lhbl1or0bb1784462c97bcad6

stolon:
  pgSuperuserName: superuser
  pgSuperuserPassword: supersecret

postgres:
  username: oisp_user
  password: supersecret

# Docket image tag
tag: latest

# Enable jaeger tracing
jaeger_tracing: false

# Sets resource limits lower to test locally
# or on smaller cluster when set to true
less_resources: true
