apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
  - port: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.numberReplicas.backend }}
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: oisp/backend:latest
        ports:
        - containerPort: 8080
        args:
        - ./wait-for-it.sh
        - hbase:2181
        - -t
        - "300"
        - --
        - make
        - runjar
        env:
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: vcap.application
              name: oisp-config
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap.services
              name: oisp-config
        workingDir: /app
      imagePullSecrets:
      - name: dockercred
