apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard
  name: dashboard
spec:
  ports:
  - port: 4001
  selector:
    app: dashboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dashboard
  name: dashboard
spec:
  replicas: {{ .Values.numberReplicas.frontend }}
  selector:
    matchLabels:
      app: dashboard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard
        image: oisp/frontend:limitless
        ports:
        - containerPort: 4001
        args:
        - ./wait-for-it.sh
        - postgres:5432
        - -t
        - "300"
        - --
        - ./wait-for-it.sh
        - redis:6379
        - -t
        - "300"
        - --
        - ./wait-for-it.sh
        - hbase-master:9090
        - -t
        - "300"
        - --
        - ./scripts/docker-start.sh
        env:
        - name: NODE_ENV
          value: local
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: vcap.application
              name: oisp-config
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap.services
              name: oisp-config
        volumeMounts:
        - mountPath: /app/keys
          name: jwt-keys
          readOnly: true
      imagePullSecrets:
        - name: dockercred
      volumes:
      - name: jwt-keys
        secret:
          defaultMode: 420
          items:
          - key: jwt.publickey
            path: public.pem
          - key: jwt.privatekey
            path: private.pem
          secretName: oisp-secrets
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dashboard-web
spec:
  rules:
  - host: k8s.streammyiot.com
    http:
      paths:
      - backend:
          serviceName: dashboard
          servicePort: 4001
