apiVersion: v1
kind: Service
metadata:
  labels:
    app: gearpump
  name: gearpump
spec:
  ports:
  - name: "8090"
    port: 8090
  selector:
    app: gearpump
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gearpump
  labels:
    app: gearpump
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gearpump
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gearpump
    spec:
      containers:
      - name: gearpump
        image: oisp/gearpump:latest
        command: ["/bin/bash"]
        args: ["/app/bootstrap.sh"]
        env:
        - name: VCAP_APPLICATION
          valueFrom:
            configMapKeyRef:
              key: vcap.application
              name: oisp-config
        - name: VCAP_SERVICES
          valueFrom:
            configMapKeyRef:
              key: vcap.services
              name: oisp-config
        - name: KAFKA
          value: "kafka:9092"
        - name: KAFKA_HEARTBEAT_TOPIC
          value: "heartbeat"
        - name: GEARPUMP
          value: "gearpump:8090"
        ports:
        - containerPort: 8090
          protocol: TCP
      imagePullSecrets:
      - name: dockercred
