apiVersion: v1
kind: Service
metadata:
  labels:
    app: hbase
  name: hbase
spec:
  clusterIP: None
  ports:
  - name: "2181"
    port: 2181
  - name: "8080"
    port: 8080
  - name: "8085"
    port: 8085
  - name: "9090"
    port: 9090
  - name: "9095"
    port: 9095
  - name: "16010"
    port: 16010
  - name: "60000"
    port: 60000
  - name: "60020"
    port: 60020
  selector:
    app: hbase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase
  labels:
    app: hbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hbase
    spec:
      containers:
      - name: hbase
        image: dajobe/hbase
        imagePullPolicy: Always
        ports:
        - containerPort: 2181
        - containerPort: 9090
        - containerPort: 60000
        - containerPort: 60020
        volumeMounts:
        - mountPath: /data
          name: hbase-data
      imagePullSecrets:
      - name: dockercred
      hostname: hbase
      volumes:
      - name: hbase-data
        persistentVolumeClaim:
          claimName: hbase-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
