apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  ports:
  - name: "8020"
    port: 8020
  - name: "14000"
    port: 14000
  - name: "50070"
    port: 50070
  - name: "50075"
    port: 50075
  - name: "10020"
    port: 10020
  - name: "13562"
    port: 13562
  - name: "19888"
    port: 19888

  selector:
    app: hdfs-namenode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hdfs-namenode
  name: hdfs-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - image: singularities/hadoop
        name: hdfs-namenode
        args: ["start-hadoop", "namenode"]
        env:
          - name: HDFS_USER
            value: root
        ports:
          - containerPort: 8020
          - containerPort: 14000
          - containerPort: 50070
          - containerPort: 50075
          - containerPort: 10020
          - containerPort: 13562
          - containerPort: 19888
        volumeMounts:
        - mountPath: /opt/hdfs
          name: hdfs-namenode-data
      volumes:
      - name: hdfs-namenode-data
        persistentVolumeClaim:
          claimName: hdfs-namenode-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-namenode-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
