apiVersion: v1
kind: Service
metadata:
  labels:
    app: mqtt-server
  name: mqtt-server
spec:
  ports:
  - port: 8883
  selector:
    app: mqtt-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt-server
  labels:
    app: mqtt-server
spec:
  serviceName: "mqtt-server"
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-server

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mqtt-server
    spec:
      containers:
      - name: mqtt-gateway
        image: oisp/mqtt-gateway:{{ .Values.tag }}
        args:
        - ./wait-for-it.sh
        - localhost:8883
        - -t
        - "300"
        - --
        - ./wait-for-it.sh
        - redis:6379
        - -t
        - "300"
        resources:
          {{ if .Values.less_resources }}
          limits:
            cpu: 100m
          requests:
            cpu: 100m
          {{ else }}
          limits:
            cpu: 500m
          requests:
            cpu: 500m
          {{ end }}
        env:
        - name: OISP_MQTT_GATEWAY_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: mqtt-gateway
        - name: OISP_REDIS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: redis
        volumeMounts:
        - mountPath: /app/keys
          name: jwt-keys
          readOnly: true
      - name: mqtt-broker
        image: oisp/mqtt-broker:{{ .Values.tag }}
        ports:
        - containerPort: 8883
        resources:
          {{ if .Values.less_resources }}
          limits:
            cpu: 100m
          requests:
            cpu: 100m
          {{ else }}
          limits:
            cpu: 500m
          requests:
            cpu: 500m
          {{ end }}
        env:
        - name: OISP_MQTT_BROKER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: mqtt-broker
        - name: OISP_REDIS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: oisp-config
              key: redis
        volumeMounts:
        - mountPath: /app/keys
          name: jwt-keys
          readOnly: true
      imagePullSecrets:
      - name: dockercred
      hostname: mqtt-server
      volumes:
      - name: jwt-keys
        secret:
          defaultMode: 420
          items:
          - key: jwt.publickey
            path: public.pem
          - key: jwt.privatekey
            path: private.pem
          - key: mqtt.key
            path: mqtt/mqtt_gw_secret.key
          - key: ssl.cert
            path: ssl/server.cert
          - key: ssl.key
            path: ssl/server.key
          secretName: oisp-secrets
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mqtt
spec:
  rules:
  - host: {{ .Values.hosts.mqttserver }}
    http:
      paths:
      - backend:
          serviceName: mqtt-server
          servicePort: 8883
