apiVersion: v1
data:
  postgres.database: oisp
  postgres.username: oisp
  vcap.application: '{ "space_name": "local" }'
  vcap.services: '{ "postgresql93": [{ "credentials": { "dbname": "oisp", "hostname":
    "postgres", "password": "password", "port": "5432", "username": "oisp" }, "name":
    "mypostgres" }], "websocket-server": [{ "server-name": "websocket-server", "name":
    "mywsserver" }], "hbase": [{ "credentials": { "HADOOP_CONFIG_KEY": { "hadoop.security.authentication":
    "simple", "hadoop.security.authorization": "false", "hbase.security.authentication":
    "simple", "ha.zookeeper.quorum": "zookeeper", "hbase.zookeeper.property.clientPort":
    "2181", "hbase.zookeeper.quorum": "zookeeper" } }, "name": "myhbase" }], "hdfs": [{
    "credentials": { "HADOOP_CONFIG_KEY": { "ha.zookeeper.quorum": "zookeeper:2181", "hadoop.security.authorization":
    "false" } }, "name": "myhdfs" }], "kafka": [{ "credentials": { "uri": "kafka:9092"
    }, "name": "mykafka" }], "zookeeper": [{ "credentials": { "zk.cluster": "zookeeper:2181",
    "zk.node": "/tmp" }, "label": "zookeeper", "name": "myzookeeper", "plan": "local",
    "tags": [] }], "gearpump": [{ "credentials": { "username": "admin", "password":
    "admin", "dashboardUrl": "localhost:8090" }, "name": "mygearpump" }], "smtp":
    [ { "credentials": { "host": "smtp.example.com", "port": "587", "protocol": "smtp",
    "username": "username", "password": "password" }, "label": "smtp", "name": "mysmtp"
    } ], "redis": [ { "credentials": { "hostname": "redis", "port": "6379", "password":
    "" }, "label": "redis", "name": "myredis" } ], "user-provided": [{ "credentials":
    { "kdc": "localhost", "kpassword": "pass", "krealm": "realm", "kuser": "user"
    }, "name": "kerberos-service" }, { "credentials": { "hosts": "kafka:9092", "enabled":
    true, "partitions": 1, "replication": 1, "timeout_ms": 10000, "topics": { "observations":
    "metrics", "rule_engine": "rules-update", "heartbeat": {"name":"heartbeat", "interval":5000} } }, "name": "kafka-ups" }, { "credentials":
    { "host": "http://dashboard:4001", "strictSSL": false }, "name": "dashboard-endpoint-ups"
    }, { "credentials": { "captcha_test_code": "s09ef48213s8fe8fw8rwer5489wr8wd5",
    "interaction_token_permision_key": "password", "private_pem_path": "./keys/private.pem",
    "public_pem_path": "./keys/public.pem" }, "name": "dashboard-security-ups" },
    { "credentials": { "deviceMeasurementTableName": "LOCAL-AA-BACKEND_DEVICE_MEASUREMENT",
    "host": "http://backend:8080" }, "name": "backend-ups" }, { "credentials": { "sender":
    "sysadmin@localhost" }, "name": "mail-ups" }, { "credentials": { "password": "7d501829lhbl1or0bb1784462c97bcad6",
    "username": "gateway@intel.com" }, "name": "gateway-credentials-ups" }, { "credentials":
    { "password": "7d501829lhbl1or0bb1784462c97bcad6", "username": "rule_engine@intel.com"
    }, "name": "rule-engine-credentials-ups" }, { "credentials": { "password": "AgjY7H3eXztyA6AmNjI2rte446gdttgattwRRF61",
    "username": "api_actuator" }, "name": "websocket-ups" }] }'
  frontend: |
    {
    "postgresConfig": "@@OISP_POSTGRES_CONFIG",
    "redisConfig": "@@OISP_REDIS_CONFIG",
    "kafkaConfig": "@@OISP_KAFKA_CONFIG",
    "smtpConfig": "@@OISP_SMTP_CONFIG",
    "dashboardSecurityConfig": "@@OISP_DASHBOARDSECURITY_CONFIG",
    "backendHostConfig": "@@OISP_BACKENDHOST_CONFIG",
    "websocketUserConfig": "@@OISP_WEBSOCKETUSER_CONFIG",
    "mailConfig": "@@OISP_MAIL_CONFIG",
    "ruleEngineConfig": "@@OISP_RULEENGINE_CONFIG",
    "gatewayConfig": "@@OISP_GATEWAY_CONFIG"
    }
  websocket-server: |
    {
    "postgresConfig": "@@OISP_POSTGRES_CONFIG",
    "websocketUserConfig": "@@OISP_WEBSOCKETUSER_CONFIG",
    "kafkaConfig": "@@OISP_KAFKA_CONFIG",
    "uri": ""
    }
  backend: |
    {
    "tsdbName": "hbase",
    "kafkaConfig": "@@OISP_KAFKA_CONFIG",
    "zookeeperConfig": "@@OISP_ZOOKEEPER_CONFIG",
    "kerberosConfig": "@@OISP_KERBEROS_CONFIG",
    "hbaseConfig": "@@OISP_HBASE_CONFIG"
    }
  kafka: |
    {
    "uri": "kafka:9092",
    "partitions": 1,
    "replication": 1,
    "timeoutMs": 10000,
    "topicsObservations": "metrics",
    "topicsRuleEngine": "rules-update",
    "topicsHeartbeatName": "heartbeat",
    "topicsHeartbeatInterval": 5000
    }
  zookeeper: |
    {
    "zkCluster": "zookeeper:2181",
    "zkNode": "/tmp"
    }
  kerberos: |
    {
    "kdc": "localhost",
    "kpassword": "pass",
    "krealm": "realm",
    "kuser": "user"
    }
  hbase: |
    {
    "hadoopProperties": "%%OISP_HADOOP_PROPERTIES"
    }
  hadoop: |
    {
    "hadoop.security.authentication": "simple",
    "hadoop.security.authorization": "false",
    "hbase.security.authentication": "simple",
    "ha.zookeeper.quorum": "zookeeper",
    "hbase.zookeeper.property.clientPort": "2181",
    "hbase.zookeeper.quorum": "zookeeper"
    }
  postgres: |
    {
    "dbname": "oisp",
    "hostname": "postgres",
    "port": "5432",
    "username": "oisp",
    "password": "password"
    }
  redis: |
    {
    "hostname": "redis",
    "port": "6379",
    "password": ""
    }
# TODO fix this, plaintext password
  smtp: |
    {
    "host": "auth.smtp.1and1.co.uk",
    "port": "587",
    "protocol": "smtp",
    "username": "test.sender@streammyiot.com",
    "password": "xxxxx"
    }
  dashboard-security: |
    {
    "captcha_test_code": "s09ef48213s8fe8fw8rwer5489wr8wd5",
    "interaction_token_permision_key": "password",
    "private_pem_path": "./keys/private.pem",
    "public_pem_path": "./keys/public.pem"
    }
  gateway: |
    {
    "password": "7d501829lhbl1or0bb1784462c97bcad6",
    "username": "gateway@intel.com"
    }
  backend-host: |
    {
    "deviceMeasurementTableName": "LOCAL-AA-BACKEND_DEVICE_MEASUREMENT",
    "host": "http://backend:8080"
    }
  mail: |
    {
    "sender": "test.sender@streammyiot.com"
    }
  rule-engine: |
    {
    "password": "7d501829lhbl1or0bb1784462c97bcad6",
    "username": "rule_engine@intel.com"
    }
  websocket-user: |
    {
    "password": "AgjY7H3eXztyA6AmNjI2rte446gdttgattwRRF61",
    "username": "api_actuator"
    }


kind: ConfigMap
metadata:
  creationTimestamp: null
  name: oisp-config
  selfLink: /api/v1/namespaces/cloudfest-1/configmaps/oisp-config
