apiVersion: batch/v1
kind: Job
metadata:
  name: rule-engine
  labels:
    app: rule-engine
spec:
  template:
    metadata:
      labels:
        app: rule-engine
    spec:
      restartPolicy: OnFailure
      containers:
      - name: rule-engine
        image: arkocal/rule-engine-deployer
#        This should be restored after CI, temporarily disabled (and obviously the previous line
#        should be deleted
#        {{ if .Values.use_local_registry }}
#        image: registry.local:5000/oisp/rule-engine-deployer:{{ .Values.tag }}
#        {{ else }}
#        This should be restored after CI, temporarily disabled
#        image: oisp/rule-engine-deployer:{{ .Values.tag }}
#        {{ end }}
        resources:
          {{ if .Values.less_resources }}
          requests:
            cpu: 50m
          {{ else }}
          limits:
            cpu: 500m
          requests:
            cpu: 500m
          {{ end }}
        env:
        - name: OISP_RULEENGINE_CONFIG
          valueFrom:
            configMapKeyRef:
              key: rule-engine
              name: oisp-config
        - name: OISP_HBASE_CONFIG
          valueFrom:
            configMapKeyRef:
              key: hbase
              name: oisp-config
        - name: OISP_HADOOP_PROPERTIES
          valueFrom:
            configMapKeyRef:
              key: hadoop
              name: oisp-config
        - name: OISP_ZOOKEEPER_CONFIG
          valueFrom:
            configMapKeyRef:
              key: zookeeper
              name: oisp-config
        - name: OISP_KAFKA_CONFIG
          valueFrom:
            configMapKeyRef:
              key: kafka
              name: oisp-config
      imagePullSecrets:
      - name: dockercred
